%% apply LF/HF/XO:
% run applyFilters; %this is a still script for debug convenience
%% apply windowing here:
[LSA.LF.D, LSA.MF.D, LSA.HF.D] = applyWindow(LSA.LF.D, LSA.MF.D, LSA.HF.D, LSA.betaKB);
%% adapt final gain into driving functions in order to get maximum possible
% SPL for the given power limitations:
[LSA.LF.D, LSA.MF.D, LSA.HF.D] = setDrivingFunctionMaxPower(...
    LSA.LF.D, LSA.MF.D, LSA.HF.D,...
    LSA.LF.Gain, LSA.MF.Gain, LSA.HF.Gain,...
    LSA.LF.Sensitivity, LSA.MF.Sensitivity, LSA.HF.Sensitivity,...
    LSA.LF.MaxElectricPower, LSA.MF.MaxElectricPower, LSA.HF.MaxElectricPower,...
    Ac.p0, Ac.Pref);
